# see https://pre-commit.com
# HOWTO: https://www.youtube.com/watch?v=psjz6rwzMdk

# specify 
# - git repo (here https://github.com/psf/black)
# - tag (here 21.9b0)
# - which commeand to run (here black)
# # further options (here --safe)
repos:
-   repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
    -   id: black
        args: [--safe]

- repo: local
    hooks:
    - id: pytest-check
      name: pytest-check
      stages: [commit]
      types: [python]
      entry: pytest
      language: system
      pass_filenames: false
      always_run: true