# see https://pre-commit.com
# HOWTO: https://www.youtube.com/watch?v=psjz6rwzMdk
# for making it run: "pre-commit install"

repos:

- repo: local
  hooks:
  - id: pytest-check
    name: pytest-check
    stages: [commit]
    types: [python]
    entry: pytest
    language: system
    pass_filenames: false
    always_run: true

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: trailing-whitespace
  - id: check-added-large-files
  - id: check-ast
  - id: check-json
  - id: check-merge-conflict
  - id: check-xml
  - id: check-yaml
    args: ['--unsafe']  # needed for !! tags in mkdocs.yml
  - id: debug-statements
  - id: end-of-file-fixer
  - id: requirements-txt-fixer
  - id: mixed-line-ending
    args: ['--fix=auto']  # replace 'auto' with 'lf' to enforce Linux/Mac line endings or 'crlf' for Windows

- repo: https://github.com/psf/black
  rev: 22.3.0
  hooks:
  -   id: black
      args: [--safe]

- repo: https://github.com/asottile/reorder_python_imports
  rev: v3.9.0
  hooks:
  -   id: reorder-python-imports

- repo: https://github.com/PyCQA/flake8
  rev: 6.0.0
  hooks:
  - id: flake8
    args: # arguments to configure flake8
        # making isort line length compatible with black
        # https://rednafi.github.io/digressions/python/2020/04/06/python-precommit.html
        - "--max-line-length=80"
        - "--max-complexity=18"
        - "--select=B,C,E,F,W,T4,B9"
        # these are errors that will be ignored by flake8
        # check out their meaning here
        # https://flake8.pycqa.org/en/latest/user/error-codes.html
        - "--ignore=E203,E266,E501,W503,F403,F401,E402,F841,C901"
