site_name: ""

theme:
  name: "material"
  palette:
    scheme: slate
    primary: deep purple
  font:
    text: Poppins
    code: Bitter
  logo: assets/icon.png
  favicon: assets/favicon.png
  features:
    - search.highlight
    - header.autohide
    - navigation.footer

plugins:
  - mkdocstrings
  - search

nav:
  - Docs: index.md
  - How-To Guides: how-to-guide.md
  - Reference: reference.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/mj-hofmann

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences