site_name: ""

theme:
  name: "material"
  palette:
    scheme: slate
    primary: deep purple
  font:
    text: Poppins
    code: Bitter
  logo: assets/icon.png
  favicon: assets/favicon.png
  features:
    - search.highlight
    - search.suggest
    - search.share
    - header.autohide
    - navigation.sections
    - navigation.footer
    - navigation.top
    
repo_url: https://github.com/mj-hofmann/TAInstCalorimetry
repo_name: mj-hofmann/TAInstCalorimetry

plugins:
  - mkdocstrings
  - search
  - offline
  - git-revision-date-localized:
      enable_creation_date: true
  - git-committers:
      repository: mj-hofmann/TAInstCalorimetry
      branch: main

nav:
  - Docs: index.md
  - How-To Guides: how-to-guide.md
  - Plotting: plotting.md
  - Tian Correction: tian.md
  - Reference: reference.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/mj-hofmann
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/matthias-j-hofmann/

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  
copyright: Copyright &copy; 2023 - present Matthias Hofmann