name: my checks
on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8', '3.9']

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Preliminary Information
      run: |
        echo "The job was automatically triggered by a ${{ github.event_name }} event."
        echo "This job is now running on a ${{ runner.os }} server hosted by GitHub!"
        echo "The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
        echo "  "
        echo "github.ref = ${{ github.ref }}"
        echo "github.sha = ${{ github.sha }}"
        echo "github.event.pull_request.head.ref = ${{ github.event.pull_request.head.ref }}"
        echo "github.event.pull_request.head.sha = ${{ github.event.pull_request.head.sha }}"
        echo "github.event.pull_request.base.ref = ${{ github.event.pull_request.base.ref }}"
        echo "github.event.pull_request.base.sha = ${{ github.event.pull_request.base.sha }}"
        echo "  "